// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imkcmqvrtsrzhktbbout.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlta2NtcXZydHNyemhrdGJib3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzQ4NzIsImV4cCI6MjA2MTM1MDg3Mn0.z3wnNn-J3zefz_GXpjxIv1daBGiIvXh_gtoIany3QXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);